Repository OK-Data-Exchange/oscn, pull requests merged in 2024-04, with the labels that each got.

#242 Adjust the query to use greater than rather than between
  app/models/eviction_letter.rb
  app/services/importers/ok_election/votes.rb
Labels: bug

#243 Add unique index on oklahoma evictions
  app/models/report_oklahoma_eviction.rb
  db/migrate/20240424144144_add_unique_constraint_to_report_oklahoma_eviction.rb
  db/schema.rb
  lib/tasks/update.rake
Labels: tech debt

#222 Jw issue 1556 importer
  app/models/structure_fire_link.rb
  app/services/azure_fire_extractor.rb
  app/services/eviction_ocr/extractor.rb
  app/services/importers/structure_fire.rb
  app/services/importers/structure_fire_link.rb
  app/workers/eviction_worker.rb
  db/migrate/20240430145443_add_status_to_structure_fire_link.rb
  db/migrate/20240430164041_update_field_name_of_structure_fire_links.rb
  db/schema.rb
  lib/tasks/structure_fire.rake
  spec/factories/structure_fire_links.rb
  spec/models/structure_fire_link_spec.rb
Labels: enhancement
